export const actionTypes = {
  SET_STAGE_ONE_FORM_DATA: "SET_STAGE_ONE_FORM_DATA",
  SET_STAGE_TWO_FORM_DATA: "SET_STAGE_TWO_FORM_DATA",
  SET_STAGE_FOUR_FORM_DATA: "SET_STAGE_FOUR_FORM_DATA",
};
